### ISSUE TITLE
JSON API 1.0 rc2 plans?

### ISSUE THREAD

**Issue by backspace** [kurko/ember-json-api#67]
Hey, thanks for your work on this. I experienced some confusion when I saw in the README that it’s compatible with JSON API 1.0 rc1 because I couldn’t find any versioning on their site. I tried out the JSON structure described on their site with this adapter and it didn’t work because the `data` container, I now realise, is a change made in rc2.

So I’m wondering whether you have plans to update for rc2. Do you need any help with it?

**Comment by eneuhauser** [comment]
Hi @backspace, I ran into the same problem and went ahead and forked the repo and was able to update to the RC2 standard. All the tests are passing and I'll begin consuming this library in my own project that uses the RC2 standard.

You can checkout [my repo](https://github.com/eneuhauser/ember-json-api) until the pull request is accepted.

**Comment by realityendshere** [comment]
Hi @eneuhauser, I tried your fork of json api adapter. It definitely works a lot better with the recent changes to the JSON API spec (RC2+). Thanks for the awesome work!

One challenge I am seeing is namespace awareness. If my API endpoints all start with 'api/' (e.g. http://www.some-api-host.com/api/users and http://www.some-api-host.com/api/posts), I can set a namespace property on the adapter to prepend all request paths with 'api'. A typical request for data works exactly as expected. The problem is, when trying to load related objects, the URL contains a duplicated namespace (e.g. http://www.some-api-host.com/api/api/posts).

It looks like the cleanRoute function removes the host portion of the related URL, but leaves the namespace segment intact. Thus when subsequently trying to fetch related data, a second copy of the namespace is prepended to the request url and runs smack into a 404 error. I am taking a look at how to adjust the cleanRoute function to be namespace aware or more effectively prevent the doubled namespace in the adapter. I am hopeful your familiarity with this library will allow you to concoct a solution more quickly. Or perhaps there is already a way to configure this.

I found a hacky workaround that works for the moment. And, to reiterate, the other work you've done to improve compatibility with RC2+ seems to work so far. Thanks again for that!

**Comment by realityendshere** [comment]
Perhaps adding the following near the beginning of the buildURL method in src/json-api-adapter.js would help...?

```javascript
var namespace = get(this, 'namespace');

if (!Ember.isBlank(namespace) && route.substr(0, namespace.length) === namespace) {
  route = route.substr(namespace.length).replace(/^\//, '');
}
```

**Comment by eneuhauser** [comment]
Hi @realityendshere, I am looking into this issue. I added a namespace to the project I'm working on and everything just worked. Could you give me sample JSON of your resource with the links section? I've found it works best if the service returns the related URI. Is the issue when it only has a type and id?

Another thing I'm investigating is in the `extractRelationships` function. I believe there could be issues if the relationship doesn't have an ID.

You suggested adding logic to the `buildURL` in the adapter, but I believe this can be handled within the serializer. I should have a solution today.

**Comment by realityendshere** [comment]
Hi @eneuhauser,

I agree, it would definitely be better to adjust the serializer to address the behavior I am seeing.

I am using Ruby/Rails and the jsonapi-resources gem.

Here's a sample of a response when sending a GET request to tools.dev/api/posts:

```
{
  "data": [
    {
      "id": "5500d1cb64616e1af8020000",
      "user_id": "5500d1cb64616e1af8000000",
      "content": "I am a post. I should be protected.",
      "type": "posts",
      "links": {
        "self": "http://tools.dev/api/posts/5500d1cb64616e1af8020000",
        "user": {
          "self": "http://tools.dev/api/posts/5500d1cb64616e1af8020000/links/user",
          "related": "http://tools.dev/api/posts/5500d1cb64616e1af8020000/user",
          "type": "users",
          "id": "5500d1cb64616e1af8000000"
        }
      }
    },
    {
      "id": "5500d1cb64616e1af8030000",
      "user_id": "5500d1cb64616e1af8000000",
      "content": "No seriously. This is a big secret.",
      "type": "posts",
      "links": {
        "self": "http://tools.dev/api/posts/5500d1cb64616e1af8030000",
        "user": {
          "self": "http://tools.dev/api/posts/5500d1cb64616e1af8030000/links/user",
          "related": "http://tools.dev/api/posts/5500d1cb64616e1af8030000/user",
          "type": "users",
          "id": "5500d1cb64616e1af8000000"
        }
      }
    }
  ]
}
```

Thanks again!

**Comment by eneuhauser** [comment]
Hi @realityendshere, I was able to duplicate your issue in a new test. I greatly refactored logic for setting keys in the routes to ensure links are very specific to the appropriate resource. After the refactor, the test that was failing with duplicating the namespace passed and the code doesn't have to reference the namespace.

Please checkout my latest changes and let me know if you have any problems.

**Comment by realityendshere** [comment]
Hi @eneuhauser,

Thanks for looking into this. That's a lot of changes!

I am using ember-cli with a proxy config for XHR requests. It seems as if the latest changes try to connect directly to the API server without going through ember-cli's proxy. The result is a whole lot of cross-site security warnings when trying to retrieve related data. If I roll back to a previous commit, everything works through the proxy.

It seems as if something in the serializer may be stashing absolute URLs for related items and the result is an attempt to fetch data directly from the API server rather than ember-cli's proxy server.

I appreciate the challenge in capturing "clean" URLs while respecting the API namespace in the serializer. Again, thanks for taking a look at this.

(In case it matters, I am on Ember CLI 0.2.0, Ember Data beta.15, and Ember 1.10)

**Comment by eneuhauser** [comment]
Hi @realityendshere,

I believe you're seeing this now because the app is now actually using the related resource URL instead of hitting the default resource URL. For example, I believe my old version would go to `/api/users/5500d1cb64616e1af8000000` instead of `http://tools.dev/api/posts/5500d1cb64616e1af8020000/user`. This could have issues as the relationships get more complicated.

I'm also using ember-cli proxy and do not see the issue. I believe if you proxy as `ember serve --proxy http://tools.dev`, it will work properly without the cross site warnings. I want to maintain the absolute URL because I personally would like to have a distributed system that could point to different domains and the app follow wherever that resource may live.

Potentially, we could add a flag to enforce relative URLs, in which case we could trim off the domain.

**Comment by realityendshere** [comment]
Hi @eneuhauser,

I am indeed using `ember server --proxy http://tools.dev`. Which is why some calls to my development API work as expected. Only the relationship links run into the digital red tape.

I definitely see the need for optionally capturing the full URL of a related resource. I suppose APIs could be spread across several hosts. I guess that leads me to 3 possible options (beyond the flag/config you suggested):

1) Adjust the API to send relative URLs (I haven't read the JSON API spec too closely within the last couple of weeks, but I assume relative links are not recommended)

2) Add a `baseurl` property (or something) to the serializer that removes only the matching portion of URLs

3) Add a method for the app developer to optionally override so they can manipulate linked URLs as needed for the given environment

If the serializer is environment aware, perhaps chopping the base URL in development would be a good starting point. Then offering flags/properties/overridable methods (or a combination) to try to address the complexity of the real world would keep the code flexible.

And of course, if any of this is already in there and I just haven't found it yet... let me know!

Many thanks.

**Comment by realityendshere** [comment]
One more thing @eneuhauser:

I am now using `https://github.com/cyu/rack-cors` to allow requests from anywhere. I still get `Content Security Policy directive` warnings from, I assume, Ember CLI content security policy. The large blocks of red text in the JS console are mildly irritating, but I think the experimental app I have going is correctly fetching data.

This works for entirely local development where I have the ability to manipulate security settings. Developers with API servers outside their control would probably still need some way to selectively use relative URLs.

I was also wondering if the proxy setting from Ember CLI is readable by the serializer. That would certainly reduce the need for extra configuration in development.

**Comment by eneuhauser** [comment]
@realityendshere,

In the serializer, I just added a method `removeHost` that will strip out the host. By default, it will use relative URLs. If someone needs absolute URLs, they can override that method with `removeHost: function(url) { return url; }`.

I really appreciate your feedback. I'm glad someone is able to use my updates.

**Comment by realityendshere** [comment]
Thank you, @eneuhauser !

That change works for me! It's always good to see a JS console with minimal red text.

And the `removeHost` method seems like it would make it reasonably easy to address a broad variety of simple or complex API hosting scenarios. Awesome!

I hope your work finds its way into the main repo now that JSON API spec is on the verge of 1.0. Thanks again!

**Comment by jonkoops** [comment]
Maybe we should close this issue since a pull request has been made for RC3?
